name = "TupleVecs"
uuid = "165f1ec4-e0fe-4040-a14f-238e8d88417a"
authors = ["Steven G. Johnson <stevenj@mit.edu>"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
